### ISSUE TITLE
Regression: Stuck on loading after adding Product Extra

### ISSUE THREAD

**Issue by jennbrewer** [lemonstand/lscloud-theme-meyer#273]
Never loads the product extra.

[Example](https://meyer.lemonstand.com/product/acre-floor-lamp)

<img width="572" alt="screen shot 2017-10-30 at 10 06 59 am" src="https://user-images.githubusercontent.com/6082087/32175175-7db12758-bd5a-11e7-9aaa-35a1effb82cd.png">

**Comment by rudy-sasquatchstudio** [comment]
@jennbrewer having a hard time reproducing this one.  The example page loads fine for us.  We were noticing a JS error appear in the console.  Not sure if it is related though.  Can I have some more details around this one please.  IE. what browser are you using and what version.  Does this issue occur on initial load of the product page or when you click on an extra?  

Thanks for the help.

Rudy

**Comment by dhalarewich** [comment]
Note that I am not able to reproduce this either using the link above, in Chrome on Mac.

**Comment by dhalarewich** [comment]
@rudy-sasquatchstudio The https://meyer.lemonstand.com/product/acre-floor-lamp store was just updated to use what's in the Master branch here. The issue seems easy to reproduce now. Just use the link above and check an Extra.

Be sure that the store you're using to test uses the latest version of Meyer, which is not what's found in production. You'll have to download Master as a .zip and import as a new theme.
