### ISSUE TITLE
Show featured ad tile in products dropdown menu Theme Setting not working

### ISSUE THREAD

**Issue by jennbrewer** [lemonstand/lscloud-theme-meyer#274]
Theme Settings checkbox **Show featured ad tile in products dropdown menu** doesn't do anything.

Shows on the older theme version:

<img width="848" alt="screen shot 2017-10-30 at 10 16 15 am" src="https://user-images.githubusercontent.com/6082087/32175450-6775943c-bd5b-11e7-9398-e313ec97fc7e.png">

**Comment by rudy-sasquatchstudio** [comment]
Just to be clear the expected result should take you to this page - https://meyer.lemonstand.com/products?

**Comment by jennbrewer** [comment]
Users are able to add the text in here themselves but the yellow banner isn't showing in the dropdown navigation when checked.

<img width="970" alt="screen shot 2017-11-01 at 3 16 30 pm" src="https://user-images.githubusercontent.com/6082087/32292831-ac715dec-bf17-11e7-92a9-cd7a890ad96b.png">

**Comment by jennbrewer** [comment]
@dhalarewich This yellow banner was showing on the older version - not on the new version. It's in the dropdown menu under Products.

**Comment by dhalarewich** [comment]
@rudy-sasquatchstudio I believe you had some details on this?

**Comment by rudy-sasquatchstudio** [comment]
@jennbrewer still not able to reproduce this...  @dhalarewich this was with a fresh theme uploaded to our store.  Verified several fresh theme uploads including the latest master version from GitHub and was not able to reproduce.

<img width="397" alt="screen shot 2017-11-18 at 11 40 13 pm" src="https://user-images.githubusercontent.com/24289426/32988479-6c152bf6-ccba-11e7-912b-d34c1af4929e.png">

<img width="1170" alt="screen shot 2017-11-18 at 11 40 51 pm" src="https://user-images.githubusercontent.com/24289426/32988480-6e6a6218-ccba-11e7-9ed7-9fb22f3d5cc8.png">

This is all the theme uploads we tried

<img width="972" alt="screen shot 2017-11-18 at 11 45 37 pm" src="https://user-images.githubusercontent.com/24289426/32988495-dbaa4a78-ccba-11e7-8c0e-d843b5197bba.png">

**Comment by dhalarewich** [comment]
Confirmed that this bug is in Chrome, but not Safari or FireFox. In the previous version of Meyer, this panel was visible in Chrome (see original ticket message) as well.

<img width="902" alt="home___meyer_and_home___meyer" src="https://user-images.githubusercontent.com/1108337/33226143-ad452e84-d13b-11e7-9b28-f80b6a2c6b5f.png">

**Comment by dhalarewich** [comment]
Issue appears to be related to ad blocking extensions hiding this. Likely because of the `.featured-ad` class name that's used.

To resolve, let's just change that class name in the HTML and all associated CSS styles.

Something innocuous like `.featured-panel` or .`featured-block` should work.

Please test against these extensions:

- https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom
- https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb

**Comment by jennbrewer** [comment]
That solved it!
